### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Vaimo\ComposerPatches\Patch\Definition\Value\Analyser' 

### ISSUE THREAD

**Issue by ytorbyk** [vaimo/composer-patches#12]
Hi,
Thank you for the nice plugin!

I got php fatal error with the new version 3.25.

`PHP Fatal error:  Uncaught Error: Class 'Vaimo\ComposerPatches\Patch\Definition\Value\Analyser' not found in /Users/ytorbyk/Sandbox/m2ce/vendor/vaimo/composer-patches/src/Patch/Definition/ExploderComponents/LabelVersionConfigComponent.php:19`

**Comment by ytorbyk** [comment]
Thanks for so quick fix.

**Comment by allanpaiste** [comment]
Yeah sorry for messing it up :(
