### ISSUE TITLE
How to patch a package from another?

### ISSUE THREAD

**Issue by boobaa** [vaimo/composer-patches#13]
I have a root composer.json which requires two packages, and package B depends on (requires) package A. In order to be able to use package B properly, package A needs to be patched.

How to instruct vaimo/composer-patches from package B's composer.json to patch package A? It would be the best if the root composer.json wouldn't contain these instructions.

**Comment by allanpaiste** [comment]
the format for adding patches into a package is exactly the same that you'd use in root composer.json.

So in your case package B would have this:
```json
{
    "extra": {
        "patches": {
            "A": {
                "Compatibility: required change to create magic": "patches/compatibility-with-dependency-a.patch"
            }
        }
    }
}
```
... where you'd have <package B root>/patches/compatibility-with-dependency-a.patch 

Note that you can test it out if you have the composer-patches module installed and execute...

```shell
composer patch --redo --from-source --filter compatibility-with-dependency-a
```

**Comment by boobaa** [comment]
Thanks for your quick answer, works like a charm! Could it also be added to the documentation, please? :)

**Comment by allanpaiste** [comment]
I'm glad that you got it working :) Added this Q/A as an example to the readme + clarified where the definition format can be used @ 554abba8dc03a29f5a08b8b5c8d507095c1b9d29
