### ISSUE TITLE
Add option to composer.json to fail builds when patching failed

### ISSUE THREAD

**Issue by ihor-sviziev** [vaimo/composer-patches#16]
I see that this plugin allow to fail build when some env variable is set to 1, however in real projects - it's better to fail composer installation even when developer just applies patch on his machine.
in https://github.com/cweagans/composer-patches there are two options - pass variable OR set extra parameter in composer.json. I think it's a good idea to add such parameter to this plugin also.

**Comment by allanpaiste** [comment]
true that. overall I think no one wants a half-patched project, so it might be better to make it a default value and allow graceful run with a flag instead. 

"patch-graceful"

How does that sound?

```json
{
  "extra": {
    "patcher": {
      "__comment": "this would make it possible to go through the patch-apply run even if some patches fail"  
      "graceful": true
    }
  }
}
```

**Comment by allanpaiste** [comment]
This has been a long time coming, but now the default behaviour is to HALT on first patch failure.

https://github.com/vaimo/composer-patches/releases/tag/4.0.0
