### ISSUE TITLE
"patches applied" field removes after composer update --lock

### ISSUE THREAD

**Issue by ihor-sviziev** [vaimo/composer-patches#18]
Hi,

After `composer update` we have in composer.lock file changes with adding "patches applied" field that shows status of applied patches.
However if we'll remove `vendor` directory and run `composer update --lock` (just update hash) - these changes will be reverted in composer.lock file, but patches will be applied.

**Comment by allanpaiste** [comment]
Hi!

I'm not sure if I fully follow. I did try to repeat what you're saying and did not really reach any conclusion on what should be changed in the source code.

Could you maybe provide steps on how I could repeat it. Let's imagine that the project ht

**Comment by allanpaiste** [comment]
Was able to reproduce.

Had to rework the whole thing that relates to composer.lock -- basically the module uses package "extra" for tracking which patches are applied, but I'm personally very happy if that only happens on installed.json side of things.

Lock - starting from 3.33.0 and 4.2.0 - should no longed receive any changes at all when patches get applied.

**Comment by ihor-sviziev** [comment]
Hi @allanpaiste,
I just was able to test your change using module versoin 4.7.0 and found that right now sometimes we're getting "extra" parameters added and sometimes - removed.

Here is example:
![capture 2018-10-22 at 15 25 20](https://user-images.githubusercontent.com/1873745/47292272-1f225f80-d60f-11e8-8037-74fe7863b97f.png)

I used `composer require <module>` and `composer update --lock` commands

So original issue with appearing `patches_applied` was fixed, but not fullly

**Comment by allanpaiste** [comment]
Yup. Have noticed that one as well. I think it relates to the new implementation of the composer.lock sanitizer which does not remove the parent level node when it's empty.

**Comment by allanpaiste** [comment]
Resolved since 3.39.0; It's - again - not perfect way of resolving this - but the new solution imitates the way empty "extra" blocks are treated in normal Composer run: they're not kept around (previously: were kept, even when empty).

**Comment by allanpaiste** [comment]
Resolved since 3.39.0; It's - again - not perfect way of resolving this - but the new solution imitates the way empty "extra" blocks are treated in normal Composer run: they're not kept around (previously: were kept, even when empty).
