### ISSUE TITLE
note that patch is a required util

### ISSUE THREAD

**Issue by jlsjonas** [vaimo/composer-patches#30]
Note that `patch` (the CLI tool) is a prerequisite for patch-package.
We didn't have it on one of our production systems and were wondering why the deploy failed.

also note that it just failed with couldn't apply patch instead of a command not found indication.

**Comment by allanpaiste** [comment]
Fixed in 3.47.1 & 4.16.1;

The error given when none of the patch appliers are available should now make it clear what the real issue is; None of the patches are being processed; Called "sanity check" in the code-base.

**Comment by allanpaiste** [comment]
Fixed in 3.47.1 & 4.16.1;

The error given when none of the patch appliers are available should now make it clear what the real issue is; None of the patches are being processed; Called "sanity check" in the code-base.
