### ISSUE TITLE
Use drupol/phposinfo

### ISSUE THREAD

**Issue by drupol** [vaimo/composer-patches#32]
Hi !

It seems that tivie/php-os-detector is a dependency. It can produces false results, see the corresponding issue: https://github.com/tivie/php-os-detector/issues/3

Based on this, I've created my own package: [drupol/phposinfo](https://packagist.org/packages/drupol/phposinfo) that fixes the issue.

This issue is to propose the replacement of tivie/php-os-detector with drupol/phposinfo.

**Comment by allanpaiste** [comment]
I'm totally on board with this switch, but there's a small problem. The main value of the whole plugin usually stems from someone wanting to patch older software, thus the low PHP version requirement (>= 5.3). I'd rather not lose that which makes me wonder if you'd be willing to branch the code to have two majors: one for older PHP (that'd just remain in maintenance) and newer one that would be the one that you currently have :/

**Comment by allanpaiste** [comment]
Currently keeping the use of tivie's package due to the need of for keeping lower php version support around (patcher module mostly used on systems that require some fix for discontinued components to be back-ported).

**Comment by drupol** [comment]
Hi,

I release a version for PHP 5.6.

Let me know if you change your mind.

thx
