### ISSUE TITLE
Problem with apply patch with new files added

### ISSUE THREAD

**Issue by ecomteck** [vaimo/composer-patches#34]
I try create patch for added new file to vendor packages.
![image](https://user-images.githubusercontent.com/35588299/62763212-386c9d80-bab5-11e9-8b45-1ef9b9493c89.png)
However after apply patch it throw error. What format for this case?
Thanks
Ecomteck

**Comment by allanpaiste** [comment]
Could your try it so that you'd change the targeted file specification to:

```
--- /dev/null
+++ Model/Indexer/CacheCleaner.php
```

It would also help to get the verbose output for `composer patch:apply` run to see the error messages from the underlying processes that actually apply the patch.

**Comment by ecomteck** [comment]
Hi i just updated by your comment. However i found new problem
![image](https://user-images.githubusercontent.com/35588299/62769083-80de8800-bac2-11e9-8bf6-fe5abd964c02.png)
Could you check that error.
Thanks
Ecomteck

**Comment by ecomteck** [comment]
This is my patch
[patch.patch.txt](https://github.com/vaimo/composer-patches/files/3485704/patch.patch.txt)

**Comment by allanpaiste** [comment]
seems that there's more to that patch than just that one file. The thing that fails is actually the next part of the patch that relates to etc/di.xml 

I'd take from the "patch unexpectedly ends in middle of line", that there might be one 
extra line missing in the end of the patch. 

(Sidenote: that 'UNKNOWN' label there is a bug and it should actually mention the process step than failed. Does not relate to this issue though)

**Comment by allanpaiste** [comment]
Error output improved in [4.17.0](https://github.com/vaimo/composer-patches/blob/master/CHANGELOG.md#4170-2019-08-11) & [3.48.0](https://github.com/vaimo/composer-patches/blob/master/CHANGELOG.md#3480-2019-08-11) where the error encountered is more clearly highlighted even when running with non-verbose mode.

In this case it'll report the 'patch unexpectedly ends in middle of line'.
