### ISSUE TITLE
Drop support of old php versions

### ISSUE THREAD

**Issue by ihor-sviziev** [vaimo/composer-patches#35]
Hi,

According to https://www.php.net/supported-versions.php - currently supported only php 7.1, actually even php 7.1 will be supported only for a 3 months.

Is there any reason for supporting php 5.3 prior to php 7.1?

**Comment by allanpaiste** [comment]
Reason for keeping it compatible with 5.3 comes from the fact that the main need for patching something rises from wanting to back-port fixes to older software. 

Ideally you'd not want to have any patches in your project when it consists of only packages that are still actively developed and supported as all the fixes and modifications would ideally be part of official releases.

There's not much to win from upgrading the code and taking into account the nature of the package, it'll provide support to as wide range of projects as possible.

**Comment by ihor-sviziev** [comment]
Ok, understood. Thank you!
