### ISSUE TITLE
Cannot be used with PHP version over 5.6

### ISSUE THREAD

**Issue by ronald2wing** [vaimo/composer-patches#37]
drupol/phposinfo 1.6.1.2 requires php ^5.3 || ^5.4 || ^5.5 || ^5.6 -> your PHP version (7) does not satisfy that requirement.

The dependency does not allow php version over 5.6.

**Comment by allanpaiste** [comment]
@drupol, why exactly is there such a constrain in place? :/

**Comment by drupol** [comment]
Hi,

drupol/phposinfo 1.6.1.2 [requires](https://packagist.org/packages/drupol/phposinfo#1.6.1.2) php ^5.3 || ^5.4 || ^5.5 || ^5.6
drupol/phposinfo 1.6.1 [requires](https://packagist.org/packages/drupol/phposinfo#1.6.1) php >= 7.1.3

Here's how I work with my branches:

* Develop in master branch (for PHP >= 7.1.3)
* Tag a new release, ex: 1.7.0
* Create a new branch 1.7.0.0
* Apply the previous branch 1.6.0.0 on it to ensure php compatibility with lower versions of PHP.
* Tag a new release 1.7.0.1

I wasn't able to find a better branching model for maintaining a package working with different versions of PHP.

Let me know if I can improve this so it works for you.

Thanks.

**Comment by drupol** [comment]
I guess just updating the composer.json from

        `"drupol/phposinfo": "^1.6.1.2",`

to

        `"drupol/phposinfo": "^1.6.1",`

Will be sufficient to get it working for all the PHP versions.

**Comment by allanpaiste** [comment]
Yup one of the things there is indeed the fact that the constraint is defined in such a strict manner. Will change that. 

The version that is not covered after making this change though: 7.0

I'd take that the version that works on 5.X would work just fine on 7.0 as well (if the constraints on said package could be expanded a bit.

**Comment by drupol** [comment]
Hi,

I just tagged 1.6.1.3 to support PHP 7.0.

**Comment by allanpaiste** [comment]
Solved in [4.19.2](https://github.com/vaimo/composer-patches/blob/master/CHANGELOG.md#4192-2019-09-02) & [3.50.2](https://github.com/vaimo/composer-patches/blob/master/CHANGELOG.md#3502-2019-09-02)

**Comment by drupol** [comment]
Thanks :)

**Comment by allanpaiste** [comment]
Thank you as well :)
