### ISSUE TITLE
patch: unrecognized option `--verbose' (FreeBSD)

### ISSUE THREAD

**Issue by puggan** [vaimo/composer-patches#38]
**Pre-requisites**
1. Have a project with patches
2. have patch applier at version 'patch 2.0-12u11 FreeBSD'

**To Reproduce**
1. composer patch:apply -vvv

**Expected**
No errors

**Actual**
Executing command (content/plugins/autoptimize/): /usr/bin/patch -t --verbose -p'1' --no-backup-if-mismatch --dry-run < '[site-path]/patches/autoptimize/2.5.1/html-fix-no-style-in-footer.patch'
      patch: unrecognized option `--verbose'
      usage: patch [-bCcEeflNnRstuv] [-B backup-prefix] [-D symbol] [-d directory]
                   [-F max-fuzz] [-i patchfile] [-o out-file] [-p strip-count]
                   [-r rej-name] [-V t | nil | never | none] [-x number]
                   [-z backup-ext] [--posix] [origfile [patchfile]]
             patch <patchfile

**Notes**
Works fine with 'GNU patch 2.7.6', that i have on my local machine, but not on the FreeBSD version at the server.

**Comment by allanpaiste** [comment]
I guess the no-backup flag is somewhat irrelevant.

The other one I'm more worried about. I'm not sure how noisy the output is on that release of 'patch', but the --verbose there is in place to be able to catch the situations where some patches get partly ignored or when a patch reversal is performed (back-ported feature in form of a patch applied against upgraded application where the patch originates from).

**Comment by puggan** [comment]
Sugestion:
* Add a FAQ section in the readme-file, and add a "How do I use composer-patches with FreeBSD patch", and add the above workaround.
* Also add a TOC to the readme-file, it a bit long, so its hard to find in it.

**Comment by allanpaiste** [comment]
Issue addressed (and docs split to at least a bit smaller manageable pieces) in [4.20.0](https://github.com/vaimo/composer-patches/blob/master/CHANGELOG.md#4200-2019-09-16) and [3.51.0](https://github.com/vaimo/composer-patches/blob/master/CHANGELOG.md#3510-2019-09-16).

**Comment by allanpaiste** [comment]
In other news: have been aware for a while that there's a PHP-implementation of patch applier floating around for quite some time. Started working towards making that as a third fallback patch applier when the current appliers fail :)

https://github.com/vaimo/unified-diff-patcher
