### ISSUE TITLE
composer patch:apply misses a --no-scripts option

### ISSUE THREAD

**Issue by c33s** [vaimo/composer-patches#42]
running `composer patch:apply --from-source -vvv` always triggers the `post-install-cmd` which installs node modules, create symlinks, ...

all this sometimes not needed after patching but this plugin does not support the `--no-scripts` options the prevent to call the composer scripts

**Comment by allanpaiste** [comment]
Solved in:

https://github.com/vaimo/composer-patches/releases/tag/3.52.0
https://github.com/vaimo/composer-patches/releases/tag/4.21.0
