### ISSUE TITLE
Empty needle

### ISSUE THREAD

**Issue by kjellholmqvist** [vaimo/composer-patches#47]
When we tried to uninstall Klarna on our M2.3.3 project, we got an exception strpos() Empty Needle. We made a patch here, just in case $item was blank/null we returned false: \Vaimo\ComposerPatches\Package\ConfigAnalyser::ownsNamespace

**Expected**
No error when running composer functions

**Actual**
`$aja project remove-module klarna/m2-checkout
Dependency "composer/composer" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)            
Package operations: 0 installs, 1 update, 8 removals
  - Removing phpxmlrpc/phpxmlrpc (4.4.1)
Removing Phpxmlrpc/Phpxmlrpc
  [ErrorException]        
  strpos(): Empty needle  `

**Notes**
I didn't figure out What caused a blank $item in that function...

**Comment by allanpaiste** [comment]
Could you check the verbose output of the Composer run by:

a) removing the klarna/m2-checkout from the project composer.json require list manually
b) running composer update klarna/m2-checkout -vvv

That would give a bit more information -hopefully - about where exactly the issue happened? 

Overall - I guess it's a good call to just make a silent decision there because the funtion is only used in current state for checking which package owns the namespace of the patches plugin.

Would appreciate though if the fix was done directly to the official release :)

**Comment by pierrotevrard-idp** [comment]
Some logs

```
(...)

Package operations: 2 installs, 30 updates, 2 removals
Installs: log1x/sage-svg:v1.0.4, log1x/sage-directives:v1.1.6
Updates: symfony/var-dumper:v5.0.3, symfony/debug:v4.4.3, symfony/translation:v5.0.3, nesbot/carbon:2.29.1, illuminate/contracts:v6.13.0, illuminate/support:v6.13.0, symfony/finder:v4.4.3, illuminate/filesystem:v6.13.0, illuminate/container:v6.13.0, illuminate/events:v6.13.0, illuminate/view:v6.13.0, illuminate/log:v6.13.0, symfony/process:v4.4.3, symfony/console:v4.4.3, illuminate/console:v6.13.0, illuminate/config:v6.13.0, illuminate/cache:v6.13.0, league/flysystem:1.0.63, ligue-hmc.lu/ligue-hmc_wp-theme_sage:dev-master, wpackagist-plugin/advanced-gutenberg:2.3.3, wpackagist-plugin/redirection:4.6.2, wpackagist-plugin/safe-svg:1.9.8, wp-cli/wp-cli:dev-master bc37f66, wp-cli/widget-command:v2.0.3, symfony/filesystem:v4.4.3, seld/phar-utils:1.0.2, composer/semver:1.5.1, composer/ca-bundle:1.2.6, composer/composer:1.9.2, roots/acorn:dev-master 58ec37c
Removals: asm89/twig-cache-extension, altorouter/altorouter


  [ErrorException]
  strpos(): Empty needle


Exception trace:
 () at .\vendor\vaimo\composer-patches\src\Package\ConfigAnalyser.php:30
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 strpos() at .\vendor\vaimo\composer-patches\src\Package\ConfigAnalyser.php:30
 Vaimo\ComposerPatches\Package\ConfigAnalyser->Vaimo\ComposerPatches\Package\{closure}() at n/a:n/a
 array_filter() at .\vendor\vaimo\composer-patches\src\Package\ConfigAnalyser.php:31
 Vaimo\ComposerPatches\Package\ConfigAnalyser->ownsNamespace() at .\vendor\vaimo\composer-patches\src\Package\OperationAnalyser.php:28
 Vaimo\ComposerPatches\Package\OperationAnalyser->isPatcherUninstallOperation() at .\vendor\vaimo\composer-patches\src\Plugin.php:129
 Vaimo\ComposerPatches\Plugin->resetPackages() at n/a:n/a
 call_user_func() at ./bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:176

(...)
```

Please, just assume that $item can be empty and avoid warning
