### ISSUE TITLE
Support for Composer 2

### ISSUE THREAD

**Issue by allanpaiste** [vaimo/composer-patches#59]
New major version for Composer is on the horizon and will introduce new plugin API:

https://php.watch/articles/composer-2#plugin-api-2

**Describe the solution you'd like**
Make sure that this plugin complies to said changes (probably requires new MAJOR release).

**Comment by hostep** [comment]
According to https://github.com/composer/composer/issues/8726#issuecomment-691097291, this is the top 26th used composer plugin not yet supporting composer 2. Would be nice if this can get resolved some day 🙂. The first release candidate for composer 2 was released about 2 weeks ago btw: https://github.com/composer/composer/releases/tag/2.0.0-RC1

Thanks for the great work btw! Been using this as a replacement of https://github.com/cweagans/composer-patches for about a 4 months now, very happy with the switch so far!

**Comment by hostep** [comment]
Hi @allanpaiste 

Now that composer v2 is released, are there plans to start supporting it in the near future?

Thanks a lot!

**Comment by deoomen** [comment]
Any news? Support for composer 2 would be great.

**Comment by hostep** [comment]
Hi @BarnyShergold, sorry to include you but we briefly talked on Slack about this.
Do you have an update around this, any chance this will get worked on in the near future?

Thanks!

**Comment by BarnyShergold** [comment]
@hostep - I checked today and whilst this repo IS still under maintenance and development and WILL be updated to support Composer 2 (I've seen the ticket list!) there is no timeline when this will happen. Sorry I can't be the bearer of better news

**Comment by hostep** [comment]
I'd like to emphasise the urgency here. We are using this module for many Magento 2 shops. Magento 2.4.2 which is going to be [released in 3 weeks](https://devdocs.magento.com/release/) [will support](https://github.com/magento/devdocs/pull/8474/files) composer version 2 and I'm not sure if their dependencies will be able to keep working on composer version 1. So it could be that we won't be able to use Magento 2.4.2 in combination with this module if composer v2 support isn't added here quickly.

**Comment by hostep** [comment]
This module was once forked from https://github.com/cweagans/composer-patches, so maybe [their changes](https://github.com/cweagans/composer-patches/compare/1.6.7...1.7.0) to make it compatible with composer v2 are enough to make this module work as well, but this module is more complex so I'm not sure.

Unfortunately I haven't got time myself to figure this out, maybe within a couple of weeks, but not in the short run.

**Comment by hostep** [comment]
I attempted bringing in support for composer v2 but I think I will give up because it's too hard for somebody who's not familiar with this codebase or with composer's internals. Hoping that the changes I did manage to make turn out to be useful for somebody else who likes to attempt this: https://github.com/vaimo/composer-patches/pull/63

**Comment by allanpaiste** [comment]
Resolved in:

* [3.53.0](https://github.com/vaimo/composer-patches/releases/tag/3.53.0)
* [4.22.0](https://github.com/vaimo/composer-patches/releases/tag/4.22.0)

**Comment by andriyun** [comment]
Thank you very much

**Comment by hostep** [comment]
Thank you very much @allanpaiste!
