### ISSUE TITLE
Possibility to disable this composer plugin from executing

### ISSUE THREAD

**Issue by hostep** [vaimo/composer-patches#74]
**Is your feature request related to a problem? Please describe.**
Hi

I have a very specific case where I would like all composer plugins to still execute during `composer install` and `composer update`, just not this one.
As far as I know, in composer we only have the possibility to disable all plugins at once with the `--no-plugins` flag but not specific ones.

**Describe the solution you'd like**
Maybe introduce [an extra environment variable](https://github.com/vaimo/composer-patches/blob/master/docs/ENVIRONMENT.md) to stop the plugin from acting?

**Describe alternatives you've considered**
None yet

**Additional context**
We have a custom application which runs every night over all our projects and tries to update all dependencies to the latest available version and generates a report based on how well this works. The application often fails on trying to apply patches
by this plugin because if we update a package to the latest version, a patch might no longer apply cleanly to it.
Also, since the composer v2 compatble version of this plugin was created, and we update this plugin itself to the latest version, it always crashes with `Argument 1 passed to Vaimo\ComposerPatches\Patch\DefinitionList\LoaderComponents\DownloaderComponent::__construct() must be an instance of Composer\Composer, instance of Composer\Package\CompletePackage given`. Only a second execution of `composer install/update` works without an error.
If we have a flag to not execute this plugin, we can work around this issue I hope.

I'd understand it if you don't want to implement this, since this is a very specific case which probably nobody else needs 🙂

**Comment by allanpaiste** [comment]
I don't think that adding additional environment variable is too far out there :)

**Comment by hostep** [comment]
Let me close this issue.

[Composer 2.2.x](https://blog.packagist.com/composer-2-2/) comes with a feature to mark plugins to allow or not allow to execute: https://getcomposer.org/doc/06-config.md#allow-plugins

That would allow me to mark this plugin not to execute when I don't want it to 👍
