### ISSUE TITLE
php 8.1 deprecation error: Passing null to parameter

### ISSUE THREAD

**Issue by staabm** [vaimo/composer-patches#89]
**Pre-requisites**
when building phpstan on php 8.1 a deprecation notice is emitted

**To Reproduce**
1. git clone https://github.com/phpstan/phpstan-src.git
2. `composer update`

**Expected**
no php8.1 errors

**Actual**

```
Deprecation Notice: explode(): Passing null to parameter #2 ($string) of type string is deprecated in C:\dvl\Workspace\phpstan-src-staabm\vendor\vaimo\composer-patches\src\Patch\SourceLoaders\PatchesSearch.php:234
```

**Env**

running on windows11x64 with

```
$ php -v
PHP 8.1.1 (cli) (built: Dec 15 2021 10:36:13) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.1, Copyright (c), by Zend Technologies
```

**Comment by peterjaap** [comment]
Same issue. I suspect more people will come here in the upcoming weeks since Magento 2.4.4 has been released today and now supports PHP 8.1.

**Comment by peterjaap** [comment]
I don't know why the issue talks about phpstan, but same issue applies for this package.

**Comment by staabm** [comment]
thanks
