### ISSUE TITLE
Parse error: syntax error, unexpected 'LIST' (T_LIST)

### ISSUE THREAD

**Issue by mougrim** [vaimo/composer-patches#9]
Hi!
Many thanks for your changes! Composer-patches became more configurable and useful.
I have next problem:
For php5.5 and php5.6 (maybe other old versions) there is next [problem:](https://travis-ci.org/mougrim/soft-mocks/jobs/340361801)
```php
PHP Parse error:  syntax error, unexpected 'LIST' (T_LIST) in vendor/vaimo/composer-patches/src/Factories/PatchesRepositoryFactory.php on line 50.
```
The problem is with constant `LIST` in file _[src/Config.php](../blob/3.22.4/src/Config.php#L13)_, which is keyword in php.
There is `"php": ">=5.3.0"` in _[composer.json](../blob/3.22.4/composer.json#L13)_, so it looks like should be supported.
I suggest to rename constant to PATCHES_LIST. I would create pull request with constant renaming if you say, what new names of constants.

Also it would be great to add tests for all supported versions, and run it using [travis-ci](https://travis-ci.org/), or something like this.

**Comment by allanpaiste** [comment]
Oh no :(

Renamed the constants @ https://github.com/vaimo/composer-patches/commit/62c85faa127c3a2c4b019247c66ddd45a3ddda52#diff-c3d642502951dfaf9e602a449a0323d9L50

I hear you loud and clear about having automated functional testing in place to avoid this!

**Comment by mougrim** [comment]
@allanpaiste, many thanks for fast fix!

**Comment by PastisD** [comment]
Hello, 
there is the same problem with PHP 5.6.x
`PHP Parse error:  syntax error, unexpected 'NEW' (T_NEW) in \vendor\vaimo\composer-patches\src\Utils\PatchListUtils.php on line 201`

**Comment by allanpaiste** [comment]
Constant renamed in 3.33.0 & 4.2.0
